### ISSUE TITLE
Estruturação das pastas

### ISSUE THREAD

**Issue by guiimarques18** [DukeOmni/br-ufg-as2020-soldout#2]
As pastas não estão estruturadas conforme solicitado no documento, exemplo:
2
2.1
2.2
...

**Comment by DukeOmni** [comment]
Fixed

**Comment by guiimarques18** [comment]
Ainda não está como gostaria...

Exemplo:
![image](https://user-images.githubusercontent.com/1537504/98290768-ddac4500-1f88-11eb-9a1a-273c48f13111.png)

![image](https://user-images.githubusercontent.com/1537504/98290788-e8ff7080-1f88-11eb-8734-e16a8a5564ca.png)
